"""Builds a self-contained HTML report of a corpus's Phase 1 + Phase 2
results -- condensation, cluster results, and a run summary, as its own
cleanly styled page.
"""

import datetime
import html as html_lib

esc = html_lib.escape


def build_cluster_results_html(phase1_state) -> str:
    cluster_defs = phase1_state.get("clusterDefs", [])
    if not cluster_defs:
        return "<p><em>No Phase 1 clusters available.</em></p>"

    items = []
    for cluster in cluster_defs:
        stems = ", ".join(f"<code>{esc(s)}</code>" for s in cluster.get("stems", []))
        ngrams = cluster.get("ngrams", [])
        ngrams_html = ""
        if ngrams:
            ngrams_html = (
                '<div style="margin-top:4px;font-size:0.85em;color:#666;">'
                "<strong>N-grams:</strong> "
                + ", ".join(f"<code>{esc(g)}</code>" for g in ngrams)
                + "</div>"
            )
        items.append(
            f'<li style="margin-bottom:10px;"><strong>{esc(cluster["name"])}</strong>'
            f"<br>{stems}{ngrams_html}</li>"
        )

    return f'<ul style="padding-left:1.2em;">{"".join(items)}</ul>'


def build_optional_material_html(phase1_state, corpus_name, rates, paths) -> str:
    lines = [f"<p>Generated by PEEL-Local for <strong>{esc(corpus_name)}</strong>.</p>"]

    if rates:
        rates_str = ", ".join(f"{r}%" for r in sorted(rates))
        lines.append(f"<p>Condensation rate(s) generated: {rates_str}.</p>")
    else:
        lines.append("<p>No condensation generated for this corpus yet.</p>")

    lines.append(
        "<p>Every interactive decision made while producing this notebook's "
        "content (Phase 1 term/cluster review, Phase 2 condensation setup, "
        "injection classification review) is logged at:</p>"
        f"<p><code>{esc(str(paths.decisions_log('phase1')))}</code><br>"
        f"<code>{esc(str(paths.decisions_log('phase2')))}</code></p>"
    )
    return "\n".join(lines)

_PAGE_STYLE = """
<style>
  :root { color-scheme: light dark; }
  body {
    font-family: Georgia, serif;
    max-width: 900px;
    margin: 2.5rem auto;
    padding: 0 1.5rem 4rem;
    line-height: 1.7;
    color: #1c1a18;
    background: #fdfcfa;
  }
  header.report-header {
    border-bottom: 2px solid #1a5c7a;
    margin-bottom: 1.5rem;
    padding-bottom: 0.8rem;
  }
  header.report-header h1 {
    font-family: system-ui, sans-serif;
    font-size: 1.6rem;
    margin: 0 0 0.2rem;
    color: #1a5c7a;
  }
  header.report-header p {
    font-family: system-ui, sans-serif;
    color: #666;
    font-size: 0.9rem;
    margin: 0;
  }
  section.report-section {
    margin: 2.2rem 0;
  }
  section.report-section > h2 {
    font-family: system-ui, sans-serif;
    font-size: 1.15rem;
    color: #1a5c7a;
    border-bottom: 1px solid #d0e4ed;
    padding-bottom: 0.3rem;
  }
  @media (prefers-color-scheme: dark) {
    body { background: #16181c; color: #e6e2d8; }
    header.report-header { border-bottom-color: #5aa9d6; }
    header.report-header h1, section.report-section > h2 { color: #7cc0ec; }
    header.report-header p { color: #9aa0a6; }
    section.report-section > h2 { border-bottom-color: #2a3138; }
  }
</style>
"""


def build_standalone_report(phase1_state, fragment, corpus_name, rate, paths) -> str:
    """Returns a complete, self-contained HTML page combining the
    condensation fragment, Phase 1's cluster results, and a run summary.
    The condensation fragment itself is already valid inline-style HTML
    (from condensation_report.build_condensation_fragment) so it's
    embedded as-is."""
    generated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    cluster_html = build_cluster_results_html(phase1_state)
    optional_html = build_optional_material_html(phase1_state, corpus_name, [rate], paths)

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{esc(corpus_name)} -- PEEL-Local Report ({rate}%)</title>
{_PAGE_STYLE}
</head>
<body>
<header class="report-header">
  <h1>{esc(corpus_name)} -- Condensation Report</h1>
  <p>{rate}% condensation &middot; generated {generated_at}</p>
</header>

<section class="report-section">
  <h2>Condensation</h2>
  {fragment}
</section>

<section class="report-section">
  <h2>Phase 1 semantic clusters</h2>
  {cluster_html}
</section>

<section class="report-section">
  <h2>Run summary</h2>
  {optional_html}
</section>

</body>
</html>"""


def save_standalone_report(html: str, path) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
