"""Auto-fills resources/PEEL-TemplateSN.html's genuinely-derivable
placeholders with this corpus's Phase 1 + Phase 2 results, so the
researcher gets a ready-to-use Voyant Spyral notebook instead of manually
pasting content in.

Deliberately does NOT touch: the open-ended tool-exploration cells
(Trends, Bubblelines, Collocates Graph, Contexts, Phrases, Corpus Terms,
Documents), the bibliographic citation placeholder ("[INSERT CITATION]" --
no data available for it), or the "Researcher's Notes" section -- these
require either data this pipeline doesn't have or the researcher's own
judgment. The tool cells for Reader/Summary/Cirrus already reference
`incList`/`excListFull` as JS variables in their working code; filling
the "PASTE CELL CONFIGURATION JS HERE" cell with those variables is what
actually makes those three tools functional.

Implementation note: the template is a real Voyant/Spyral HTML export,
which stores each code cell twice -- a cached, syntax-highlighted
CodeMirror rendering (broken across many <span> tags) and the raw source
(a single <pre class="notebook-code-editor-raw ..."> block). Plain
str.replace() on exact placeholder strings only reliably matches the raw
source for multi-token placeholders (the highlighted rendering breaks
them across spans) -- which is fine, since the raw source is what Voyant
re-parses when the notebook is reopened; the cached rendering is a
cosmetic snapshot. Parsing/rewriting this file with a general HTML parser
was deliberately avoided as riskier than exact string substitution.
"""

import html as html_lib
import json

from common.paths import resources_dir

TEMPLATE_NAME = "PEEL-TemplateSN.html"

esc = html_lib.escape


def _to_js_array(items) -> str:
    return "[" + ", ".join(json.dumps(str(item)) for item in items) + "]"


def build_cluster_results_html(phase1_state) -> str:
    cluster_defs = phase1_state.get("clusterDefs", [])
    if not cluster_defs:
        return "<p><em>No Phase 1 clusters available.</em></p>"

    items = []
    for cluster in cluster_defs:
        stems = ", ".join(f"<code>{esc(s)}</code>" for s in cluster.get("stems", []))
        ngrams = cluster.get("ngrams", [])
        ngrams_html = ""
        if ngrams:
            ngrams_html = (
                '<div style="margin-top:4px;font-size:0.85em;color:#666;">'
                "<strong>N-grams:</strong> "
                + ", ".join(f"<code>{esc(g)}</code>" for g in ngrams)
                + "</div>"
            )
        items.append(
            f'<li style="margin-bottom:10px;"><strong>{esc(cluster["name"])}</strong>'
            f"<br>{stems}{ngrams_html}</li>"
        )

    return f'<ul style="padding-left:1.2em;">{"".join(items)}</ul>'


def build_optional_material_html(phase1_state, corpus_name, rates, paths) -> str:
    lines = [f"<p>Generated by PEEL-Local for <strong>{esc(corpus_name)}</strong>.</p>"]

    if rates:
        rates_str = ", ".join(f"{r}%" for r in sorted(rates))
        lines.append(f"<p>Condensation rate(s) generated: {rates_str}.</p>")
    else:
        lines.append("<p>No condensation generated for this corpus yet.</p>")

    lines.append(
        "<p>Every interactive decision made while producing this notebook's "
        "content (Phase 1 term/cluster review, Phase 2 condensation setup, "
        "injection classification review) is logged at:</p>"
        f"<p><code>{esc(str(paths.decisions_log('phase1')))}</code><br>"
        f"<code>{esc(str(paths.decisions_log('phase2')))}</code></p>"
    )
    return "\n".join(lines)


def build_voyant_notebook(phase1_state, condensation_fragment_by_rate, corpus_name, paths) -> str:
    """Returns the filled HTML for one Voyant notebook. Reads the shared
    template from resources/ and returns a new string -- the template
    file itself is never modified. `condensation_fragment_by_rate` is
    {rate: fragment_html}, normally a single entry (one notebook file per
    rate is built by the caller, one call each)."""
    template_path = resources_dir() / TEMPLATE_NAME
    template = template_path.read_text(encoding="utf-8")

    corpus_id = (phase1_state.get("corpusId") or "").strip()
    inc_list = phase1_state.get("incList", [])
    exc_list = phase1_state.get("excList", [])

    title = f"PEEL Notebook -- {corpus_name}"
    header = f"Automatically generated by PEEL-Local for corpus '{corpus_name}'."

    condensation_html = "".join(
        f"<h3>{rate}% condensation</h3>\n{frag}"
        for rate, frag in sorted(condensation_fragment_by_rate.items())
    ) or "<p><em>No condensation generated for this corpus yet.</em></p>"

    cluster_html = build_cluster_results_html(phase1_state)
    optional_html = build_optional_material_html(
        phase1_state, corpus_name, list(condensation_fragment_by_rate), paths,
    )
    config_js = (
        f"var incList = {_to_js_array(inc_list)};\n"
        f"var excListFull = {_to_js_array(exc_list)};"
    )

    replacements = {
        "PEEL TEMPLATE (YOUR TITLE GOES HERE)": title,
        "[YOUR HEADER GOES HERE]": header,
        "PASTE TEXT CONDENSATION HERE": condensation_html,
        "[INSERT OPTIONAL MATERIAL FROM PHASES 1, 2 AND 3, HERE]": optional_html,
        "// PASTE CELL CONFIGURATION JS HERE": config_js,
        "[INSERT RESULTS OF PHASE&nbsp; 1 HERE]": cluster_html,
    }
    for old, new in replacements.items():
        template = template.replace(old, new)

    if corpus_id:
        template = template.replace("var myCorpus = '';", f"var myCorpus = '{corpus_id}';")

    return template


def save_voyant_notebook(html: str, path) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
